name: Windows workflow
on:
 workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    run-on: windows-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v1

      
      - name: Run a one-line script
        run: mvn clean install
        continue-on-error: false
